name: Enviar correo diario a la hora indicada de España

on:
  schedule:
    - cron: '*/5 * * * *'  # Ejecuta cada 5 minutos
  workflow_dispatch:

jobs:
  enviar-correo:
    runs-on: ubuntu-latest
    steps:
      - name: Obtener hora actual en Madrid
        id: hora
        run: |
          hora_madrid=$(TZ=Europe/Madrid date +'%H:%M')
          echo "Hora en Madrid: $hora_madrid"
          echo "hora_madrid=$hora_madrid" >> $GITHUB_OUTPUT

      - name: Llamar a la función Netlify si es la hora deseada
        if: contains('21:59,22:00,22:01,22.02', steps.hora.outputs.hora_madrid)
        run: |
          echo "La hora coincide, llamando a Netlify..."
          curl -s -X GET "https://enviocorreosperiodico.netlify.app/.netlify/functions/enviar-correo"
