name: Enviar correo diario a la hora indicada de España

on:
  schedule:
    - cron: '* * * * *'  # Corre cada minuto
  workflow_dispatch: 

jobs:
  enviar-correo:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar si la hora es correcta en Madrid
        uses: frenck/action-rtc@v1
        id: rtc
        with:
          timezone: 'Europe/Madrid'
          hour: '13'
          minute: '42'

      - name: Llamar a la función Netlify
        if: steps.rtc.outputs.match == 'true'
        run: curl -s -X GET "https://enviocorreosperiodico.netlify.app/.netlify/functions/enviar-correo"
