name: Enviar correo diario a la hora indicada de España

on:
  schedule:
    - cron: '* * * * *'  # Corre cada minuto para pruebas
  workflow_dispatch:

jobs:
  enviar-correo:
    runs-on: ubuntu-latest
    steps:
      - name: Obtener hora local en Madrid
        id: time
        uses: igorshubovych/rtc-timezone-action@v1
        with:
          timezone: 'Europe/Madrid'

      - name: Verificar hora y enviar correo
        if: steps.time.outputs.time == '13:43'
        run: |
          echo "La hora coincide, llamando a Netlify..."
          curl -s -X GET "https://enviocorreosperiodico.netlify.app/.netlify/functions/enviar-correo"
